apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    app: catalogue
    project: roboshop
    tier: app
  ports:
    - name: catalogue
      protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port