apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    project: roboshop
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app: cart
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: cart
        project: roboshop
        tier: app
    spec:
      containers:
        - name: cart
          image: "satishkalari/cart:{{ .Values.deployment.imageVersion }}"
          imagePullPolicy: Always
          resources: 
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          envFrom:
            - configMapRef:
                name: cart-config             