apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    app: user
    project: roboshop
    tier: app
  ports:
    - name: user
      protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port