apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
  namespace: roboshop
  labels:
    app: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql