apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:        
        name: cpu
        type: Utilization
        averageUtilization: {{ .Values.hpa.averageUtilization}}
        
    # - type: Resource
    #   resource:
    #     name: memory
    #     targetAverageUtilization: 80
---