apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    app: payment
    project: roboshop
    tier: app
  ports:
    - name: payment
      protocol: TCP
      port: 8080 # Service port
      targetPort: 8080 # Container port
