apiVersion: v1
type: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  ClusterIP: None
  selector:
    app: rabbitmq
    project: roboshop
    tier: db
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
   