apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    app: cart
    project: roboshop
    tier: app
spec:
  type: ClusterIP
  selector:
    app: cart
    project: roboshop
    tier: app
  ports:
    - name: cart
      protocol: TCP
      port: 8080
      targetPort: 8080